apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: co2_data
  POSTGRES_USER: co2_user
  POSTGRES_PASSWORD: co2_password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init-sql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  schema.sql: |
    -- PostgreSQL Schema for CO2 Emissions Data Pipeline
    
    DROP TABLE IF EXISTS yearly_summary CASCADE;
    DROP TABLE IF EXISTS country_summary CASCADE;
    DROP TABLE IF EXISTS raw_emissions CASCADE;
    
    CREATE TABLE raw_emissions (
        id SERIAL PRIMARY KEY,
        country VARCHAR(100) NOT NULL,
        year INTEGER NOT NULL,
        iso_code VARCHAR(10),
        population BIGINT,
        gdp DOUBLE PRECISION,
        co2 DOUBLE PRECISION,
        co2_per_capita DOUBLE PRECISION,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(country, year)
    );
    
    CREATE INDEX idx_raw_country ON raw_emissions(country);
    CREATE INDEX idx_raw_year ON raw_emissions(year);
    CREATE INDEX idx_raw_country_year ON raw_emissions(country, year);
    
    CREATE TABLE country_summary (
        id SERIAL PRIMARY KEY,
        country VARCHAR(100) UNIQUE NOT NULL,
        iso_code VARCHAR(10),
        total_co2 DOUBLE PRECISION,
        avg_co2_per_capita DOUBLE PRECISION,
        latest_year INTEGER,
        latest_population BIGINT,
        latest_co2 DOUBLE PRECISION,
        latest_co2_per_capita DOUBLE PRECISION,
        first_year INTEGER,
        years_with_data INTEGER,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE yearly_summary (
        id SERIAL PRIMARY KEY,
        year INTEGER UNIQUE NOT NULL,
        total_global_co2 DOUBLE PRECISION,
        total_global_population BIGINT,
        avg_co2_per_capita DOUBLE PRECISION,
        num_countries INTEGER,
        max_country_co2 DOUBLE PRECISION,
        max_country_name VARCHAR(100),
        yoy_growth_rate DOUBLE PRECISION,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
